### ISSUE TITLE
pride commands (including bisexual, trans, lesbian) are working far less than they used to.

### ISSUE THREAD

**Issue by SegFault-Verm** [ishwi/Chuu#45]
9 times out of 10 chuu says `Couldn't find enough matching covers for User's pride chart`, even though it's historically worked fine for the same user.

![image](https://user-images.githubusercontent.com/69766325/113480640-4c84c000-948d-11eb-83e1-e463a6b544a4.png)

![image](https://user-images.githubusercontent.com/69766325/113480665-71793300-948d-11eb-91f0-f3901e0c84b7.png)

(Images just an example, this is an issue for more than just me)

**Comment by ishwi** [comment]
This is an ongoing issue that last.fm has with their api.  
I created a issue in their support platform almost two months ago but still isn't fixed nor acknowledged  :(
https://support.last.fm/t/user-gettopalbums-not-returning-album-artwork-with-high-values-of-limit

**Comment by ishwi** [comment]
This was not really fixed on last.fm but a  workaround exists, so this should work as before. 

Small caveat is that the workaround requires me asking for less albums at a time, so the total number of albums checked for these commands will be smaller :(
