### ISSUE TITLE
Server artists by country

### ISSUE THREAD

**Issue by rahul-ar** [ishwi/Chuu#51]
This is a feature request to add a command that would list the artists from a specific country most played by server members based on a parameter denoting the country.

**Comment by ishwi** [comment]
Added `serverfrom` and `servercountries` commands with last update. Specifically on 4c232739686386c3f82a536c22273345d1f22e5e  
Which should be equivalent to the `from` and `countries` command but for the whole server. 
I only tested on a small test bot I have and I suspect it is a very heavy command if its used on the main instance on the bot. So even though the commands are implemented Ill leave this issue open for now to track the performance of those commands.

**Comment by ishwi** [comment]
Has been working fine so im closing this one.
