### ISSUE TITLE
`--aside` is not working correctly again

### ISSUE THREAD

**Issue by emanuele6** [ishwi/Chuu#55]
Hi. After you fixed the aside bug last time, it started working correctly, but i've noticed since about 45h ago that the `--aside` option now just generates a chart with no text and no aside part (e.g. `!top --aside` behaves the same as `!top --noplays --notitles`).
 
One of the commits after 15070de6fea2a648e06d8b06ec7af0b74ab24acb must have broke it because it was working correctly for a bit.

**Comment by ishwi** [comment]
Yeah, sorry about that, should be working as intended now 😔
