### ISSUE TITLE
ISSUE REGARDING ONGOING DISCORD HACK

### ISSUE THREAD

**Issue by pmcdonough8133** [ishwi/Chuu#64]
Hi all, IAmTheBlackMetal here, I am a Chuu bot mod on discord.
I figure Ish may post something here when he has a chance but until that point I would recommend removing the official Chuu bot (local instances should be fine) from your discord and warning your users about an ongoing hack that has destroyed the Chuu server.

Details:
https://twitter.com/PhleBuster/status/1439285455267188741

I wish I had a better method for getting this info out but the server was destroyed before any of us could figure out what was going on.

**Comment by sam-ward42** [comment]
What does this link have to do with the bot? Sounds to me like someone with permissions got their account token stolen and then someone nuked the server with it

**Comment by ryandeering** [comment]
Yeah I have absolutely no idea how this relates to the bot. Sounds like typical Discord reactionary nonsense.

**Comment by pmcdonough8133** [comment]
This is exactly the case and the link is in regards to how the hack works and steps to take.  The issue is that the account that was stolen has access to the official Chuu bot and until we can fully survey the damage, we do not know if the bad actors have access to the bot and can thus use it to spread the hack through Chuu. Until that time, my best suggestion is to kick Chuu until we can confirm she is safe to use again. You can always re-add the bot later on.

**Comment by th0mk** [comment]
@sam-ward42 the account that owns both the server and the chuu bot itself was compromised through a token grabber like in the tweet. The token of the bot itself has also been changed by the hacker

**Comment by sam-ward42** [comment]
> @sam-ward42 the account that owns both the server and the chuu bot itself was compromised through a token grabber like in the tweet. The token of the bot itself has also been changed by the hacker

Yikes

**Comment by IsraelAristide** [comment]
rip

**Comment by jslpc** [comment]
Thanks for the update! I wish there was a better way to let all users of the bot know about this but I'm sure that's out of the question given the situation. Really lame stuff, hope it gets fixed soon and nothing _too_ damaging happens.

**Comment by macks2008** [comment]
Did  y'all have Malwarebytes Antimalware or Norton running by any chance? curious if antiviruses have caught on to these token grabbers yet...

**Comment by lieseld** [comment]
> Did y'all have Malwarebytes Antimalware or Norton running by any chance? curious if antiviruses have caught on to these token grabbers yet...

One of the tweets linked above mention that AVs fail to catch this yet.

**Comment by sam-ward42** [comment]
> Did y'all have Malwarebytes Antimalware or Norton running by any chance? curious if antiviruses have caught on to these token grabbers yet...

I found one of them a couple of weeks ago, downloaded it through the Discord games library and then copied the files to my virtual machine. No anti-virus I have installed on there caught it so I doubt any would rn. I reported this to Discord weeks ago. It's sad nothing has been done and it's gotten as bad as a bot developer getting caught out by it

**Comment by Prathyush-KKK** [comment]
This is just sad

**Comment by JaMeS3609** [comment]
> Hi all, IAmTheBlackMetal here, I am a Chuu bot mod on discord. I figure Ish may post something here when he has a chance but until that point I would recommend removing the official Chuu bot (local instances should be fine) from your discord and warning your users about an ongoing hack that has destroyed the Chuu server.
> 
> Details: https://twitter.com/PhleBuster/status/1439285455267188741
> 
> I wish I had a better method for getting this info out but the server was destroyed before any of us could figure out what was going on.

Hi there, I am one of the staff over at Chuu'topia, a Chuu server. We are getting a fair few people join looking for your bot, we  are going to try corral them together for now. 
Would some of your staff be interested in joining for a while to keep people updated if you intend on making another bot?

**Comment by yourfriendoss** [comment]
> > Hi all, IAmTheBlackMetal here, I am a Chuu bot mod on discord. I figure Ish may post something here when he has a chance but until that point I would recommend removing the official Chuu bot (local instances should be fine) from your discord and warning your users about an ongoing hack that has destroyed the Chuu server.
> > Details: https://twitter.com/PhleBuster/status/1439285455267188741
> > I wish I had a better method for getting this info out but the server was destroyed before any of us could figure out what was going on.
> 
> Hi there, I am one of the staff over at Chuu'topia, a Chuu server. We are getting a fair few people join looking for your bot, we are going to try corral them together for now. Would some of your staff be interested in joining for a while to keep people updated if you intend on making another bot?

Hi, I'm in a server where chuu is used 24/7, and we'd like it back. We want some like, yk news about it? Like maybe throw together a chuu support server 2?

**Comment by teiraaa** [comment]
> > > Hi all, IAmTheBlackMetal here, I am a Chuu bot mod on discord. I figure Ish may post something here when he has a chance but until that point I would recommend removing the official Chuu bot (local instances should be fine) from your discord and warning your users about an ongoing hack that has destroyed the Chuu server.
> > > Details: https://twitter.com/PhleBuster/status/1439285455267188741
> > > I wish I had a better method for getting this info out but the server was destroyed before any of us could figure out what was going on.
> > 
> > 
> > Hi there, I am one of the staff over at Chuu'topia, a Chuu server. We are getting a fair few people join looking for your bot, we are going to try corral them together for now. Would some of your staff be interested in joining for a while to keep people updated if you intend on making another bot?
> 
> Hi, I'm in a server where chuu is used 24/7, and we'd like it back. We want some like, yk news about it? Like maybe throw together a chuu support server 2?

Second this, one of my servers used Chuu a lot and this has kinda left everyone in the dark, it would be really nice to have a new server to discuss it more openly and post any new info there whenever possible. :)

**Comment by ishwi** [comment]
Hi, main developer here. 

First, I wanted to comment on why I didn't comment anything here yesterday. I was busy trying to protect and fix my system in order to protect from the hack that  I was subject to. 

Then, I have updated the README with the current status. And with the current support server in which I will try to keep everyone updated from now on.  The current server can be found in [https://discord.gg/3tYsPMWvQG](https://discord.gg/3tYsPMWvQG). 
As of now, I have sent 6 emails to the discord support, with no response. Is the only way I found that can be used for the issue that happened. So I'll try to wait if they respond and update them with all the information I can provide. 

Additionally, I would want to apologize to everyone for the problems caused, and I'm deeply sorry for what as happened. 
Hope we can sort it with the discord support shortly.

**Comment by missdeath666** [comment]
> Hi all, IAmTheBlackMetal here, I am a Chuu bot mod on discord. I figure Ish may post something here when he has a chance but until that point I would recommend removing the official Chuu bot (local instances should be fine) from your discord and warning your users about an ongoing hack that has destroyed the Chuu server.
> 
> Details: https://twitter.com/PhleBuster/status/1439285455267188741
> 
> I wish I had a better method for getting this info out but the server was destroyed before any of us could figure out what was going on.

Ahhhhh help so my dumb brain decided to click dat free nitro link and i was gonna create account and was in the middle of the process to be done then i thought what if it doesnt and its a scam tjen i left that link and where talking about hack and stuff so i downloaded an antivirus app and turned on extra protection for my discord. Idk if i will still get hacked 😭😭😭😭😭 help

**Comment by sam-ward42** [comment]
> > Hi all, IAmTheBlackMetal here, I am a Chuu bot mod on discord. I figure Ish may post something here when he has a chance but until that point I would recommend removing the official Chuu bot (local instances should be fine) from your discord and warning your users about an ongoing hack that has destroyed the Chuu server.
> > Details: https://twitter.com/PhleBuster/status/1439285455267188741
> > I wish I had a better method for getting this info out but the server was destroyed before any of us could figure out what was going on.
> 
> Ahhhhh help so my dumb brain decided to click dat free nitro link and i was gonna create account and was in the middle of the process to be done then i thought what if it doesnt and its a scam tjen i left that link and where talking about hack and stuff so i downloaded an antivirus app and turned on extra protection for my discord. Idk if i will still get hacked 😭😭😭😭😭 help

You'll be fine. Those websites just take your login details when you submit them so as long as you didn't login through the "free nitro" link you should be good. Antivirus will only protect against malicious files you've downloaded. Just be careful that links you click on are from trusted domains. A lot of fake links are similar to real ones but read links carefully and if it isn't exactly as it should be then my advice is don't click on it. And don't download anything that seems even slightly suspicious or isn't from a trusted source

**Comment by Eratuk** [comment]
i hope everything ends well, because this is a very good bot 😞

**Comment by mrbaderq** [comment]
is the bot back? i see that it is online on discord...

**Comment by ishwi** [comment]
> is the bot back? i see that it is online on discord...

No I still don't have any control over the bot nor my account. The person that has hijacked my account must have put it online, and it is 100% running a different code or functionality than of the Chuu bot, probably aimed with a malicious intent. 
Even if it doesn't send any message, it could be scanning all the messages of the servers is in trying to recover sensitive date such as pictures, passwords, credit cards that might be lying around on discord servers. 

So be aware of any possible thing that the bot might do, and as said, it is recommended to kick it from all the server that is in.

**Comment by mrbaderq** [comment]
> > is the bot back? i see that it is online on discord...
> 
> No I still don't have any control over the bot nor my account. The person that has hijacked my account must have put it online, and it is 100% running a different code or functionality than of the Chuu bot, probably aimed with a malicious intent. Even if it doesn't send any message, it could be scanning all the messages of the servers is in trying to recover sensitive date such as pictures, passwords, credit cards that might be lying around on discord servers.
> 
> So be aware of any possible thing that the bot might do, and as said, it is recommended to kick it from all the server that is in.

ok thanks, praying all goes well

**Comment by idontknowshark** [comment]
Well, that sure sucks. Any way someone could build chuu clone bot from the source code? I get that I'm asking for too much, but I really don't see any other way. RIP Chuu.

**Comment by sam-ward42** [comment]
> Well, that sure sucks. Any way someone could build chuu clone bot from the source code? I get that I'm asking for too much, but I really don't see any other way. RIP Chuu.

I'm sure if we just wait Discord will sort it out. No need to go creating another bot quite yet lol. And worst case scenario, the dev can just run Chuu on a different bot app

**Comment by Alipoodle** [comment]
You'd be glad to know that it's currently not being used for 100% bad stuff at the moment.
Just DMed a bunch of people on a YouTube Music focused group.

Currently using Masked Links to fake a "Giveaway" although it's only to a Discord server for all the links, so not like it's getting people to download anything or go to a sketchy site.
![image](https://user-images.githubusercontent.com/17199186/135924986-c2130276-1008-46db-8c68-cd3f049ab14c.png)

**Comment by th0mk** [comment]
@Alipoodle Yes, its currently being used for bad stuff/ phishing by the people that have hijacked the devs account. The developer has sent multiple emails to Discord and has tried other ways of getting in touch with support faster, but no response so far. There is no way for bot developers to get priority support so we just have to wait until Discord notices the ticket, knowing Discord this can take a while/

Also just as a reminder for everyone, do **not** click the link and do **not** enter any account details.

**Comment by macks2008** [comment]
> 
> 
> > Did y'all have Malwarebytes Antimalware or Norton running by any chance? curious if antiviruses have caught on to these token grabbers yet...
> 
> I found one of them a couple of weeks ago, downloaded it through the Discord games library and then copied the files to my virtual machine. No anti-virus I have installed on there caught it so I doubt any would rn. I reported this to Discord weeks ago. It's sad nothing has been done and it's gotten as bad as a bot developer getting caught out by it

Well that's disappointing. Might want to send that file to Malwarebytes at least, via [their reporting pipeline](https://support.malwarebytes.com/hc/en-us/articles/360038522814-Submit-a-phishing-link-malicious-website-or-file-to-Malwarebytes)? (I shouldn't need to explain why, even if I wanted that responsibility, I don't have the executable in question)

**Comment by twiggobb** [comment]
i have info that probably is new. today my friend's server had a random bot invited. i was concerned, so i checked logs. turns out, chuu created a new role with admin perms, then created a new invite, then a user (Emery#1827 user id 882855159342968842) that appears to be involved in this scamming joined, was given the new role by chuu, invited another bot (Giveaways#6864 user id 824071297935605760), then user left, and chuu bot deleted the evidence. will attach the server's logs. important info is highlighted, such as time stamps to show that this was all one event that happened at the same time. left has chuu creating role + invite, user adding bot. right has new bot creating an invite thats kinda sus, and chuu bot deleting evidence 
![CDE7F430-0678-4355-BEB6-9799C595BC26](https://user-images.githubusercontent.com/92196413/136643455-47354061-1492-4cb8-afeb-fedf22d1c434.jpeg)

**Comment by ishwi** [comment]
Since it has been finally resolved with discord support, I'm closing this issue. 
Thanks to all for the support and help during this few weeks <3.

**Comment by macks2008** [comment]
> 
> 
> Could it have hacked me if I clicked the link on my iPhone? It added me to a server and I immediately left it, I’m really worried because my Microsoft account on my phone has a lot of money spent on it and I don’t want to lose it, maybe I’m just paranoid though

you might be okay, but please for your own sake do not stop being paranoid. Paranoia makes you more careful, and that's exactly what these scammers want people not to do: think carefully.
If you're uncertain about that Microsoft account, change your password, long out of it, and log back in. If you invalidate the session token, they can't hijack the session even if they have a clone of your phone somehow (which is unlikely).
