### ISSUE TITLE
Non accurate updating. 

### ISSUE THREAD

**Issue by Lachi-lachi** [ishwi/Chuu#66]
Chuu does not keep up with the songs playing, even after disconnecting and reconnecting the account from the bot, disconnecting spotify from last fm and just restarting both apps. tried updating, claims last scribble was 41 hours ago.

**Comment by th0mk** [comment]
Last.fm is what does the music tracking, not Chuu. If you have issues with Last.fm tracking your Spotify, you should go to their support forums and follow [their guide](https://support.last.fm/t/spotify-has-stopped-scrobbling-what-can-i-do/3184) on how to fix this.
