### ISSUE TITLE
Bad dependency in build.gradle

### ISSUE THREAD

**Issue by tati1454** [ishwi/Chuu#72]
When I try to build Chuu, gradle can't find the lavaplayer-fork because the version is invalid, apparently it specifies the commit hash but in the repos of jitpack there is no package with a version specified by the git commit. There is an specific reason to use this revision? Why not just use `1.3.97`?

**Comment by ishwi** [comment]
IIRC when that hash was specify the 1.3.97 was yet to be launched, and I wanted to use some features that were not yet released on the previous stable release of the lavaplayer fork. I assume jitpack stopped tracking that hash or something.

So yeah, the dependency should probably use the proper versioning.

**Comment by ishwi** [comment]
Dependency was updated to 1.3.98.1
