### ISSUE TITLE
[BUG]: Chuu can not be used using its prefix

### ISSUE THREAD

**Issue by Nihilopia** [ishwi/Chuu#81]
### Describe the bug

Chuu doesn't react when Chuu-commands using its default or custom prefix is sent.
It only reacts to slash commands.

### Version

Public Discord bot (Default)

### More details?

What I tried already to fix it or find a workaround:
- Set the prefix explicitly to `!`
- Set the prefix to `;`
- Give chuu administrator privileges

(The prefix change was registered by Chuu)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yayuyokitano** [comment]
Prefix commands are possibly permanently gone, move to slash commands. At least for now, Chuu has not had message content intent approved and so will no longer be able to read messages in servers as discord is currently gradually making it privileged.

You can read more here: https://support-dev.discord.com/hc/en-us/articles/4404772028055-Message-Content-Privileged-Intent-FAQ
