### ISSUE TITLE
[REQ]: Tracklist slash command

### ISSUE THREAD

**Issue by haileighB** [ishwi/Chuu#82]
### Describe the feature

Hi! I don't think there is any slash command for the album tracklist (your plays of each track on an album). This was available in the prefix commands (!tl). There is already a global-tracklist slash command but I (and others) would like the one for seeing our own plays. 
Not sure if there are other commands missing to be migrated.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yayuyokitano** [comment]
The slash command equivalent of !tl is /tracks
